from examgpt.storage.base import Storage


class ChatHelper:
    def __init__(self, storage: Storage): ...

    def get_helper(self, exam_id: str): ...

    def multiple_choice(self, n: int = 1, topic: str = ""): ...

    def longform(self, n: int = 1, topic: str = ""): ...

    def answer(self, question: str): ...
